### ISSUE TITLE
where exports are saved

### ISSUE THREAD

**Issue by CSGalloway** [igorlogius/partial-bookmark-import-export#1]
1) no way to tell where exports are saved to.

FF 108.2 / windows 10 / [artial boomkmark import / export: downloaded today...

**Comment by igorlogius** [comment]
Hi @CSGalloway, 

exports are saved via the browser built-in download mechanic. 
Depending on how you configured your browser, the export file "export.json" should either be saved  into your default download directory or into your last used download directory. You should be able to access your downloads via the browser Download Button. 

![snip_20230117-084616](https://user-images.githubusercontent.com/67047467/212839122-7ea866df-ae4b-416e-8bf8-fa685c076c1a.png)
